In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("HR.csv")

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

In [5]:
df[df.satisfaction_level.isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [6]:
sl_s=df['satisfaction_level']

In [7]:
sl_s=sl_s.dropna()

In [8]:
sl_s

0        0.38
1        0.80
2        0.11
3        0.72
4        0.37
5        0.41
6        0.10
7        0.92
8        0.89
9        0.42
10       0.45
11       0.11
12       0.84
13       0.41
14       0.36
15       0.38
16       0.45
17       0.78
18       0.45
19       0.76
20       0.11
21       0.38
22       0.09
23       0.46
24       0.40
25       0.89
26       0.82
27       0.40
28       0.41
29       0.38
         ... 
14970    0.78
14971    0.39
14972    0.11
14973    0.36
14974    0.36
14975    0.10
14976    0.40
14977    0.81
14978    0.40
14979    0.09
14980    0.76
14981    0.73
14982    0.38
14983    0.72
14984    0.40
14985    0.91
14986    0.85
14987    0.90
14988    0.46
14989    0.43
14990    0.89
14991    0.09
14992    0.40
14993    0.76
14994    0.40
14995    0.37
14996    0.37
14997    0.11
14998    0.37
15001    0.70
Name: satisfaction_level, Length: 15000, dtype: float64

In [18]:
sl_s.describe()

count    15000.000000
mean         0.612839
std          0.248623
min          0.090000
25%          0.440000
50%          0.640000
75%          0.820000
max          1.000000
Name: satisfaction_level, dtype: float64

In [19]:
sl_s.skew()

-0.47643761717258093

In [21]:
sl_s.kurt()

-0.6706959323886252

In [13]:
sl_s

0        0.38
1        0.80
2        0.11
3        0.72
4        0.37
5        0.41
6        0.10
7        0.92
8        0.89
9        0.42
10       0.45
11       0.11
12       0.84
13       0.41
14       0.36
15       0.38
16       0.45
17       0.78
18       0.45
19       0.76
20       0.11
21       0.38
22       0.09
23       0.46
24       0.40
25       0.89
26       0.82
27       0.40
28       0.41
29       0.38
         ... 
14970    0.78
14971    0.39
14972    0.11
14973    0.36
14974    0.36
14975    0.10
14976    0.40
14977    0.81
14978    0.40
14979    0.09
14980    0.76
14981    0.73
14982    0.38
14983    0.72
14984    0.40
14985    0.91
14986    0.85
14987    0.90
14988    0.46
14989    0.43
14990    0.89
14991    0.09
14992    0.40
14993    0.76
14994    0.40
14995    0.37
14996    0.37
14997    0.11
14998    0.37
15001    0.70
Name: satisfaction_level, Length: 15000, dtype: float64

In [17]:
np.percentile(sl_s,[0,10,50,90,100],axis=0)

array([0.09, 0.21, 0.64, 0.92, 1.  ])

In [26]:
np.histogram(sl_s,bins=np.arange(0,1.1,0.1))

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [43]:
le_s = df["last_evaluation"]

In [30]:
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

In [34]:
le_s.quantile(0.25)

0.56

In [35]:
le_s.describe()

count     15002.000000
mean         67.373732
std        8164.407524
min           0.360000
25%           0.560000
50%           0.720000
75%           0.870000
max      999999.000000
Name: last_evaluation, dtype: float64

In [36]:
le_s.skew()

122.48265175204614

In [37]:
le_s.kurt()

15001.999986807796

In [38]:
le_s[le_s>1]

15000    999999.0
Name: last_evaluation, dtype: float64

In [44]:
le_s=le_s[le_s<=1]

In [45]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
5        0.50
6        0.77
7        0.85
8        1.00
9        0.53
10       0.54
11       0.81
12       0.92
13       0.55
14       0.56
15       0.54
16       0.47
17       0.99
18       0.51
19       0.89
20       0.83
21       0.55
22       0.95
23       0.57
24       0.53
25       0.92
26       0.87
27       0.49
28       0.46
29       0.50
         ... 
14971    0.45
14972    0.97
14973    0.52
14974    0.54
14975    0.79
14976    0.47
14977    0.85
14978    0.47
14979    0.93
14980    0.89
14981    0.93
14982    0.49
14983    0.84
14984    0.56
14985    0.99
14986    0.85
14987    0.70
14988    0.55
14989    0.57
14990    0.88
14991    0.81
14992    0.48
14993    0.83
14994    0.57
14995    0.48
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [46]:
le_s.describe()

count    15001.000000
mean         0.716068
std          0.171185
min          0.360000
25%          0.560000
50%          0.720000
75%          0.870000
max          1.000000
Name: last_evaluation, dtype: float64

In [47]:
le_s.skew()

-0.02653253746872579

In [48]:
le_s.kurt()

-1.2390454655108427

In [51]:
np.histogram(le_s,bins=np.arange(0,1.1,0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [19]:
np_s=df['number_project']

In [54]:
np_s[np_s.isnull()]

Series([], Name: number_project, dtype: int64)

In [55]:
np_s.describe()

count    15002.000000
mean         3.802693
std          1.232733
min          2.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: number_project, dtype: float64

In [56]:
np_s.skew()

0.3377744235231047

In [57]:
np_s.kurt()

-0.49580962709450604

In [59]:
np.histogram(np_s,bins=np.arange(0,8,1))

(array([   0,    0, 2391, 4055, 4365, 2761, 1430], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7]))

In [21]:
np_s.value_counts(normalize=True)

4    0.290961
3    0.270297
5    0.184042
2    0.159379
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [22]:
np_s.value_counts(normalize=True).sort_index(ascending=False)

7    0.017064
6    0.078256
5    0.184042
4    0.290961
3    0.270297
2    0.159379
Name: number_project, dtype: float64

In [24]:
amh_s=df['average_monthly_hours']

In [64]:
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

In [65]:
amh_s.describe()

count    15002.000000
mean       201.041728
std         49.941815
min         96.000000
25%        156.000000
50%        200.000000
75%        245.000000
max        310.000000
Name: average_monthly_hours, dtype: float64

In [66]:
amh_s.kurt()

-1.1350158577565719

In [67]:
amh_s.skew()

0.05322458779916304

In [26]:
np.histogram(amh_s,bins=np.arange(0,350,50))

(array([   0,   54, 2891, 4524, 4231, 3143], dtype=int64),
 array([  0,  50, 100, 150, 200, 250, 300]))

In [25]:
amh_s.value_counts(bins=np.arange(0,350,50))

(150.0, 200.0]    4474
(200.0, 250.0]    4273
(250.0, 300.0]    3043
(100.0, 150.0]    2980
(50.0, 100.0]       73
(-0.001, 50.0]       0
Name: average_monthly_hours, dtype: int64

In [74]:
amh_s[amh_s<amh_s.quantile(0.25)]

5        153
9        142
10       135
13       148
14       137
15       143
21       147
23       139
27       135
28       128
29       132
31       134
32       145
33       140
36       137
37       126
39       152
42       127
46       147
48       148
49       147
50       152
51       135
52       134
53       132
55       140
58       128
63       132
66       153
69       135
        ... 
14927    138
14928    141
14932    127
14934    155
14935    143
14937    147
14941    131
14942    135
14949    147
14951    154
14952    149
14953    149
14954    146
14956    148
14958    134
14959    155
14965    149
14967    128
14968    128
14971    140
14973    143
14974    153
14976    136
14978    144
14982    137
14984    148
14988    145
14992    155
14994    151
14996    143
Name: average_monthly_hours, Length: 3680, dtype: int64

In [75]:
amh_s[amh_s>=amh_s.quantile(0.25)]

0        157
1        262
2        272
3        223
4        159
6        247
7        259
8        224
11       305
12       234
16       160
17       255
18       160
19       262
20       282
22       304
24       158
25       242
26       239
30       294
34       246
35       255
38       306
40       269
41       158
43       281
44       276
45       182
47       273
54       307
        ... 
14955    258
14957    236
14960    257
14961    189
14962    164
14963    271
14964    280
14966    219
14969    157
14970    225
14972    310
14975    310
14977    251
14979    296
14980    238
14981    162
14983    257
14985    254
14986    247
14987    206
14989    159
14990    228
14991    257
14993    293
14995    160
14997    280
14998    158
14999    158
15000    158
15001    158
Name: average_monthly_hours, Length: 11322, dtype: int64

In [78]:
amh_s[amh_s<amh_s.quantile(0.25)][amh_s>=amh_s.quantile(0.1)]

5        153
9        142
13       148
14       137
15       143
21       147
23       139
32       145
33       140
36       137
39       152
46       147
48       148
49       147
50       152
55       140
66       153
72       149
77       137
79       142
80       140
81       151
82       139
92       143
95       155
100      154
101      147
102      150
107      148
109      155
        ... 
14900    154
14901    140
14913    137
14914    144
14915    142
14917    142
14923    148
14927    138
14928    141
14934    155
14935    143
14937    147
14949    147
14951    154
14952    149
14953    149
14954    146
14956    148
14959    155
14965    149
14971    140
14973    143
14974    153
14978    144
14982    137
14984    148
14988    145
14992    155
14994    151
14996    143
Name: average_monthly_hours, Length: 2283, dtype: int64

In [81]:
amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

0        157
1        262
2        272
3        223
4        159
5        153
6        247
7        259
8        224
9        142
10       135
11       305
12       234
13       148
14       137
15       143
16       160
17       255
18       160
19       262
20       282
21       147
22       304
23       139
24       158
25       242
26       239
27       135
28       128
29       132
        ... 
14972    310
14973    143
14974    153
14975    310
14976    136
14977    251
14978    144
14979    296
14980    238
14981    162
14982    137
14983    257
14984    148
14985    254
14986    247
14987    206
14988    145
14989    159
14990    228
14991    257
14992    155
14993    293
14994    151
14995    160
14996    143
14997    280
14998    158
14999    158
15000    158
15001    158
Name: average_monthly_hours, Length: 15002, dtype: int64

In [83]:
amh_s.value_counts(bins=np.arange(amh_s.min(),amh_s.max()+10,10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

In [84]:
tsc_s=df['time_spend_company']

In [85]:
tsc_s[tsc_s.isnull()]

Series([], Name: time_spend_company, dtype: int64)

In [86]:
tsc_s.describe()

count    15002.000000
mean         3.498067
std          1.460053
min          2.000000
25%          3.000000
50%          3.000000
75%          4.000000
max         10.000000
Name: time_spend_company, dtype: float64

In [88]:
tsc_s.skew()

1.8535304537020056

In [90]:
tsc_s.kurt()

4.77435277319063

In [91]:
tsc_s.value_counts().sort_index()

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

In [92]:
wa_s=df['Work_accident']

In [93]:
wa_s.value_counts().sort_index()

0    12833
1     2169
Name: Work_accident, dtype: int64

In [94]:
wa_s.describe()

count    15002.000000
mean         0.144581
std          0.351689
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Work_accident, dtype: float64

In [95]:
l_s=df['left']

In [96]:
l_s.value_counts().sort_index()

0    11428
1     3574
Name: left, dtype: int64

In [97]:
pl5_s=df['promotion_last_5years']

In [98]:
pl5_s.value_counts().sort_index()

0    14683
1      319
Name: promotion_last_5years, dtype: int64

In [114]:
s_s=df['salary']

In [100]:
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

In [113]:
s_s.where(s_s=="nme")

15001    nme
Name: salary, dtype: object

In [107]:
s_s[s_s=='nme']

15001    nme
Name: salary, dtype: object

In [109]:
s_s=s_s[s_s!='nme']

In [118]:
s_s=s_s.where(s_s!='nme').dropna().sort_values()

In [117]:
s_s

0           low
1        medium
2        medium
3           low
4           low
5           low
6           low
7           low
8           low
9           low
10          low
11          low
12          low
13          low
14          low
15          low
16          low
17          low
18          low
19          low
20          low
21          low
22          low
23          low
24          low
25          low
26          low
27          low
28          low
29          low
          ...  
14972    medium
14973    medium
14974    medium
14975    medium
14976    medium
14977    medium
14978    medium
14979    medium
14980      high
14981       low
14982    medium
14983    medium
14984    medium
14985    medium
14986       low
14987       low
14988       low
14989       low
14990       low
14991       low
14992       low
14993       low
14994       low
14995       low
14996       low
14997       low
14998       low
14999       low
15000       low
15001       nme
Name: salary, Length: 15

In [110]:
s_s.value_counts()

low       7318
medium    6446
high      1237
Name: salary, dtype: int64

In [27]:
d_s=df['department']

In [28]:
d_s.where(d_s!='sale')

0             sales
1             sales
2             sales
3             sales
4             sales
5             sales
6             sales
7             sales
8             sales
9             sales
10            sales
11            sales
12            sales
13            sales
14            sales
15            sales
16            sales
17            sales
18            sales
19            sales
20            sales
21            sales
22            sales
23            sales
24            sales
25            sales
26            sales
27            sales
28       accounting
29       accounting
            ...    
14972    accounting
14973    accounting
14974    accounting
14975            hr
14976            hr
14977            hr
14978            hr
14979     technical
14980     technical
14981     technical
14982     technical
14983     technical
14984     technical
14985     technical
14986     technical
14987     technical
14988     technical
14989     technical
14990       support


In [29]:
d_s[d_s!='sale']

0             sales
1             sales
2             sales
3             sales
4             sales
5             sales
6             sales
7             sales
8             sales
9             sales
10            sales
11            sales
12            sales
13            sales
14            sales
15            sales
16            sales
17            sales
18            sales
19            sales
20            sales
21            sales
22            sales
23            sales
24            sales
25            sales
26            sales
27            sales
28       accounting
29       accounting
            ...    
14970         sales
14971         sales
14972    accounting
14973    accounting
14974    accounting
14975            hr
14976            hr
14977            hr
14978            hr
14979     technical
14980     technical
14981     technical
14982     technical
14983     technical
14984     technical
14985     technical
14986     technical
14987     technical
14988     technical


In [124]:
d_s=d_s.where(d_s!='sale').dropna()

In [120]:
d_s.value_counts(normalize=True)

sales          0.275963
technical      0.181309
support        0.148647
IT             0.081789
product_mng    0.060125
marketing      0.057192
RandD          0.052460
accounting     0.051127
hr             0.049260
management     0.041994
sale           0.000133
Name: department, dtype: float64

In [127]:
df=df.dropna(axis=0,how='any')

In [129]:
df=df[df.last_evaluation<=1][df.salary!='nme'][df.department!='sale']

C:\Users\ni\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [130]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14969                0.43             0.46               2   
14970                0.78             0.93               4   
14971                0.39             0.45               2   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

In [132]:
df.groupby('department').mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294

In [134]:
df.loc[:,['department','last_evaluation']].groupby('department').mean()

last_evaluation
department                  
IT                  0.716830
RandD               0.712122
accounting          0.717718
hr                  0.708850
management          0.724000
marketing           0.715886
product_mng         0.714756
sales               0.709717
support             0.723109
technical           0.721099

In [135]:
df.loc[:,['department','average_monthly_hours']].groupby('department')['average_monthly_hours'].apply(lambda x:x.max()-x.min())

department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64

In [32]:
df['average_monthly_hours'].groupby(df['department']).apply(lambda x:x.max()-x.min())

department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sale             0
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64

In [19]:
t = pd.DataFrame({'11':[1,2,3],'22':[3,4,np.nan]})
t.replace(np.nan,0)
t['11'] =1
''

ValueError: max() arg is an empty sequence