In [3]:
import numpy as np
import pandas as pd 
import scipy.stats as ss

C:\Users\ni\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ni\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
df = pd.DataFrame({'A':['a0','a1','a1','a2','a3','a4'],'B':['b0','b1','b2','b2','33',None],'C':[1,2,None,3,4,5],'D':[0.1,10.2,11.4,8.9,9.1,12],'E':[10,19,32,25,8,None],'F':['f0','f1','g2','f3','f4','f5']})

In [7]:
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [8]:
df.isnull()

A      B      C      D      E      F
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False   True  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False   True  False  False   True  False

In [9]:
df.dropna()

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
3  a2  b2  3.0   8.9  25.0  f3
4  a3  33  4.0   9.1   8.0  f4

In [12]:
df.dropna(subset=['B'])

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
2  a1  b2  NaN  11.4  32.0  g2
3  a2  b2  3.0   8.9  25.0  f3
4  a3  33  4.0   9.1   8.0  f4

In [14]:
df.duplicated(['A'])

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [15]:
df.duplicated(['A','B'])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [16]:
df.drop_duplicates(['A'])

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [18]:
df.drop_duplicates(['A','B'])

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [26]:
df.drop_duplicates('A',keep='last')

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [27]:
df.drop_duplicates('A',keep='first')

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [28]:
df.drop_duplicates('A',keep=False)

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [29]:
df.fillna('b*')

A   B   C     D   E   F
0  a0  b0   1   0.1  10  f0
1  a1  b1   2  10.2  19  f1
2  a1  b2  b*  11.4  32  g2
3  a2  b2   3   8.9  25  f3
4  a3  33   4   9.1   8  f4
5  a4  b*   5  12.0  b*  f5

In [32]:
df.fillna(df['E'].mean())

A     B     C     D     E   F
0  a0    b0   1.0   0.1  10.0  f0
1  a1    b1   2.0  10.2  19.0  f1
2  a1    b2  18.8  11.4  32.0  g2
3  a2    b2   3.0   8.9  25.0  f3
4  a3    33   4.0   9.1   8.0  f4
5  a4  18.8   5.0  12.0  18.8  f5

In [33]:
df.interpolate()

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  2.5  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   8.0  f5

In [34]:
df['E'].interpolate()

0    10.0
1    19.0
2    32.0
3    25.0
4     8.0
5     8.0
Name: E, dtype: float64

In [35]:
pd.Series([1,None,4,5,20]).interpolate()

0     1.0
1     2.5
2     4.0
3     5.0
4    20.0
dtype: float64

In [42]:
df['E'].interpolate(method='spline',order=3)

0    10.000000
1    19.000000
2    32.000000
3    25.000000
4     8.000000
5   -20.143603
Name: E, dtype: float64

In [45]:
low_q=df['D'].quantile(0.25)
high_q=df['D'].quantile(0.75)
q_int=high_q-low_q
k=1.5
df[df['D']>(low_q-q_int*k)][df['D']<(high_q+q_int*k)]

C:\Users\ni\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """


A     B    C     D     E   F
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [46]:
df.drop(2)

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [52]:
df['F'].values

array(['f0', 'f1', 'g2', 'f3', 'f4', 'f5'], dtype=object)

In [56]:
df[[True if item.startswith('f') else False for item in df['F'].values]]

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    33  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [59]:
df = pd.DataFrame({'A':ss.norm.rvs(size=10),'B':ss.norm.rvs(size=10),'C':ss.norm.rvs(size=10),'D':np.random.randint(high=2,low=0,size=10)})
df

A         B         C  D
0  1.438838 -0.457094  0.517078  1
1  1.800088  1.703093  0.773639  1
2  1.169899  1.838783  1.275987  1
3 -0.252417  1.657207  1.379596  1
4 -0.738267  1.407704  1.549361  0
5  0.545445  0.435707 -0.015296  1
6  1.653309 -0.316289  0.023268  1
7  1.050963 -0.221998  0.996486  1
8  0.372953 -1.510818 -1.546277  0
9  0.822841  1.906744 -1.837440  0

In [62]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel

In [72]:
X=df.loc[:,['A','B','C']]
X

A         B         C
0  1.438838 -0.457094  0.517078
1  1.800088  1.703093  0.773639
2  1.169899  1.838783  1.275987
3 -0.252417  1.657207  1.379596
4 -0.738267  1.407704  1.549361
5  0.545445  0.435707 -0.015296
6  1.653309 -0.316289  0.023268
7  1.050963 -0.221998  0.996486
8  0.372953 -1.510818 -1.546277
9  0.822841  1.906744 -1.837440

In [66]:
Y=df.loc[:,['D']]

In [68]:
skt=SelectKBest(k=2)
skt.fit(X,Y)

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SelectKBest(k=2, score_func=<function f_classif at 0x0000005FEE82C950>)

In [71]:
skt.transform(X)

array([[ 1.43883755,  0.51707751],
       [ 1.8000881 ,  0.77363934],
       [ 1.16989943,  1.275987  ],
       [-0.25241651,  1.37959553],
       [-0.73826721,  1.549361  ],
       [ 0.54544479, -0.01529578],
       [ 1.65330948,  0.02326827],
       [ 1.05096315,  0.99648566],
       [ 0.37295254, -1.54627742],
       [ 0.82284088, -1.83744002]])

In [73]:
rfe=RFE(estimator=SVR(kernel='linear'),n_features_to_select=2)
rfe.fit_transform(X,Y)

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 1.43883755,  0.51707751],
       [ 1.8000881 ,  0.77363934],
       [ 1.16989943,  1.275987  ],
       [-0.25241651,  1.37959553],
       [-0.73826721,  1.549361  ],
       [ 0.54544479, -0.01529578],
       [ 1.65330948,  0.02326827],
       [ 1.05096315,  0.99648566],
       [ 0.37295254, -1.54627742],
       [ 0.82284088, -1.83744002]])

In [74]:
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)
sfm.fit_transform(X,Y)

array([[ 1.43883755,  0.51707751],
       [ 1.8000881 ,  0.77363934],
       [ 1.16989943,  1.275987  ],
       [-0.25241651,  1.37959553],
       [-0.73826721,  1.549361  ],
       [ 0.54544479, -0.01529578],
       [ 1.65330948,  0.02326827],
       [ 1.05096315,  0.99648566],
       [ 0.37295254, -1.54627742],
       [ 0.82284088, -1.83744002]])

In [75]:
lst= [6,8,10,15,16,24,25,40,67]

In [77]:
pd.qcut(lst,q=3)

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 24.333], (13.333, 24.333], (13.333, 24.333], (24.333, 67.0], (24.333, 67.0], (24.333, 67.0]]
Categories (3, interval[float64]): [(5.999, 13.333] < (13.333, 24.333] < (24.333, 67.0]]

In [78]:
pd.qcut(lst,q=3,labels=['low','medium','high'])

[low, low, low, medium, medium, medium, high, high, high]
Categories (3, object): [low < medium < high]

In [80]:
pd.cut(lst,bins=3)

[(5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (26.333, 46.667], (46.667, 67.0]]
Categories (3, interval[float64]): [(5.939, 26.333] < (26.333, 46.667] < (46.667, 67.0]]

In [81]:
pd.cut(lst,bins=3,labels=['low','medium','high'])

[low, low, low, low, low, low, low, medium, high]
Categories (3, object): [low < medium < high]

In [82]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [85]:
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1, 1))

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.  ],
       [0.15],
       [0.45],
       [0.7 ],
       [1.  ]])

In [86]:
StandardScaler().fit_transform(np.array([1,1,1,1,0,0,0,0]).reshape(-1,1))

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [87]:
StandardScaler().fit_transform(np.array([1,0,0,0,0,0,0,0]).reshape(-1,1))

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ni\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 2.64575131],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

In [88]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [89]:
LabelEncoder().fit_transform(np.array(['Up','Down','Down','Up']))

array([1, 0, 0, 1], dtype=int64)

In [90]:
LabelEncoder().fit_transform(np.array(['Low','Medium','High','Medium','Low']))

array([1, 2, 0, 2, 1], dtype=int64)

In [91]:
lb_encoder = LabelEncoder()

In [92]:
lb_tran_f=lb_encoder.fit_transform(np.array(['Red','Yellow','Blue','Green']))

In [102]:
lb_tran_f

array([2, 3, 0, 1], dtype=int64)

In [94]:
oht_encoder=OneHotEncoder().fit(lb_tran_f.reshape(-1,1))

C:\Users\ni\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [104]:
oht_encoder.transform(lb_encoder.transform(np.array(['Yellow','Blue','Green','Green','Red'])).reshape(-1,1)).toarray()

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [107]:
from sklearn.preprocessing import Normalizer

In [109]:
Normalizer(norm='l1').fit_transform(np.array([1,1,3,-1,2]).reshape(-1,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.]])

In [111]:
Normalizer(norm='l1').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.125,  0.125,  0.375, -0.125,  0.25 ]])

In [112]:
Normalizer(norm='l2').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.25,  0.25,  0.75, -0.25,  0.5 ]])

In [1]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [5]:
X=np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
Y=np.array([1,1,1,2,2,2])

In [6]:
LinearDiscriminantAnalysis(n_components=1).fit_transform(X,Y)

array([[-1.73205081],
       [-1.73205081],
       [-3.46410162],
       [ 1.73205081],
       [ 1.73205081],
       [ 3.46410162]])

In [7]:
clf=LinearDiscriminantAnalysis(n_components=1).fit(X,Y)

In [13]:
clf.predict([[0.5,1]])

array([2])

In [14]:
from sklearn.decomposition import PCA

C:\Users\ni\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [16]:
PCA(n_components=1).fit_transform(X)

array([[ 1.38340578],
       [ 2.22189802],
       [ 3.6053038 ],
       [-1.38340578],
       [-2.22189802],
       [-3.6053038 ]])